AWSTemplateFormatVersion: '2010-09-09'
Description: 'GitHub Actions OIDC IAM Role and Policy for Troop 202 Website Infrastructure'

Parameters:
  GitHubOrg:
    Type: String
    Default: 'peter-mxtoolbox'
    Description: 'GitHub organization or username'
  
  GitHubRepo:
    Type: String
    Default: 'Troop202Website'
    Description: 'GitHub repository name'
  
  GitHubBranch:
    Type: String
    Default: 'main'
    Description: 'GitHub branch that can assume the role'
  
  RoleName:
    Type: String
    Default: 'GitHubActions-Troop202-Role'
    Description: 'Name for the IAM role'

Resources:
  # GitHub OIDC Identity Provider
  GitHubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1  # GitHub Actions OIDC thumbprint
        - 1c58a3a8518e8759bf075b76b750d4f2df264fcd  # Backup thumbprint
      Tags:
        - Key: Name
          Value: 'GitHub Actions OIDC Provider'
        - Key: Project
          Value: 'Troop202Website'
        - Key: ManagedBy
          Value: 'CloudFormation'

  # IAM Policy for GitHub Actions
  GitHubActionsPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub '${RoleName}-Policy'
      Description: 'Policy for GitHub Actions to deploy Troop 202 infrastructure'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: CloudFormationAccess
            Effect: Allow
            Action:
              - 'cloudformation:*'
            Resource: '*'
          
          - Sid: S3Access
            Effect: Allow
            Action:
              - 's3:*'
            Resource:
              - 'arn:aws:s3:::*troop202*'
              - 'arn:aws:s3:::*troop202*/*'
              - 'arn:aws:s3:::*'
          
          - Sid: S3ListAccess
            Effect: Allow
            Action:
              - 's3:ListAllMyBuckets'
              - 's3:GetBucketLocation'
            Resource: '*'
          
          - Sid: CloudFrontAccess
            Effect: Allow
            Action:
              - 'cloudfront:CreateDistribution'
              - 'cloudfront:GetDistribution'
              - 'cloudfront:GetDistributionConfig'
              - 'cloudfront:UpdateDistribution'
              - 'cloudfront:DeleteDistribution'
              - 'cloudfront:TagResource'
              - 'cloudfront:UntagResource'
              - 'cloudfront:ListTagsForResource'
              - 'cloudfront:CreateOriginAccessControl'
              - 'cloudfront:GetOriginAccessControl'
              - 'cloudfront:UpdateOriginAccessControl'
              - 'cloudfront:DeleteOriginAccessControl'
              - 'cloudfront:ListOriginAccessControls'
              - 'cloudfront:CreateResponseHeadersPolicy'
              - 'cloudfront:GetResponseHeadersPolicy'
              - 'cloudfront:UpdateResponseHeadersPolicy'
              - 'cloudfront:DeleteResponseHeadersPolicy'
              - 'cloudfront:CreateInvalidation'
              - 'cloudfront:GetInvalidation'
              - 'cloudfront:ListInvalidations'
              - 'cloudfront:ListDistributions'
            Resource: '*'
          
          - Sid: CertificateManagerAccess
            Effect: Allow
            Action:
              - 'acm:RequestCertificate'
              - 'acm:DescribeCertificate'
              - 'acm:ListCertificates'
              - 'acm:AddTagsToCertificate'
              - 'acm:ListTagsForCertificate'
              - 'acm:DeleteCertificate'
              - 'acm:GetCertificate'
            Resource: '*'
            Condition:
              StringEquals:
                'aws:RequestedRegion': 'us-east-1'
          
          - Sid: Route53Access
            Effect: Allow
            Action:
              - 'route53:GetChange'
              - 'route53:GetHostedZone'
              - 'route53:ListHostedZones'
              - 'route53:ListHostedZonesByName'
              - 'route53:ListResourceRecordSets'
              - 'route53:ChangeResourceRecordSets'
              - 'route53:GetHealthCheck'
              - 'route53:ListHealthChecks'
            Resource: '*'
          
          - Sid: WAFAccess
            Effect: Allow
            Action:
              - 'wafv2:CreateWebACL'
              - 'wafv2:GetWebACL'
              - 'wafv2:UpdateWebACL'
              - 'wafv2:DeleteWebACL'
              - 'wafv2:TagResource'
              - 'wafv2:UntagResource'
              - 'wafv2:ListTagsForResource'
              - 'wafv2:AssociateWebACL'
              - 'wafv2:DisassociateWebACL'
              - 'wafv2:ListWebACLs'
              - 'wafv2:GetWebACLForResource'
            Resource: '*'
          
          - Sid: CloudWatchAccess
            Effect: Allow
            Action:
              - 'logs:*'
              - 'cloudwatch:*'
            Resource: '*'
          
          - Sid: KMSAccess
            Effect: Allow
            Action:
              - 'kms:CreateKey'
              - 'kms:CreateAlias'
              - 'kms:DeleteAlias'
              - 'kms:DescribeKey'
              - 'kms:GetKeyPolicy'
              - 'kms:PutKeyPolicy'
              - 'kms:TagResource'
              - 'kms:UntagResource'
              - 'kms:ListAliases'
              - 'kms:ListKeys'
              - 'kms:Encrypt'
              - 'kms:Decrypt'
              - 'kms:ReEncrypt*'
              - 'kms:GenerateDataKey*'
              - 'kms:DescribeKey'
            Resource: '*'
          
          - Sid: SSMParameterAccess
            Effect: Allow
            Action:
              - 'ssm:PutParameter'
              - 'ssm:GetParameter'
              - 'ssm:GetParameters'
              - 'ssm:DeleteParameter'
              - 'ssm:AddTagsToResource'
              - 'ssm:RemoveTagsFromResource'
              - 'ssm:ListTagsForResource'
              - 'ssm:GetParametersByPath'
            Resource:
              - !Sub 'arn:aws:ssm:*:${AWS::AccountId}:parameter/troop202/*'
          
          - Sid: IAMAccess
            Effect: Allow
            Action:
              - 'iam:GetRole'
              - 'iam:GetRolePolicy'
              - 'iam:ListAttachedRolePolicies'
              - 'iam:ListRolePolicies'
              - 'iam:PassRole'
              - 'iam:CreateRole'
              - 'iam:DeleteRole'
              - 'iam:UpdateRole'
              - 'iam:AttachRolePolicy'
              - 'iam:DetachRolePolicy'
              - 'iam:PutRolePolicy'
              - 'iam:DeleteRolePolicy'
              - 'iam:CreatePolicy'
              - 'iam:DeletePolicy'
              - 'iam:GetPolicy'
              - 'iam:ListPolicies'
              - 'iam:TagRole'
              - 'iam:UntagRole'
            Resource: '*'

  # IAM Role for GitHub Actions
  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      Description: 'IAM Role for GitHub Actions to deploy Troop 202 website infrastructure'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref GitHubOIDCProvider
            Action: 'sts:AssumeRoleWithWebIdentity'
            Condition:
              StringEquals:
                'token.actions.githubusercontent.com:aud': 'sts.amazonaws.com'
              StringLike:
                'token.actions.githubusercontent.com:sub': 
                  - !Sub 'repo:${GitHubOrg}/${GitHubRepo}:ref:refs/heads/${GitHubBranch}'
                  - !Sub 'repo:${GitHubOrg}/${GitHubRepo}:pull_request'
                  - !Sub 'repo:${GitHubOrg}/${GitHubRepo}:ref:refs/heads/*'
      ManagedPolicyArns:
        - !Ref GitHubActionsPolicy
      MaxSessionDuration: 3600
      Tags:
        - Key: Name
          Value: !Ref RoleName
        - Key: Project
          Value: 'Troop202Website'
        - Key: GitHubOrg
          Value: !Ref GitHubOrg
        - Key: GitHubRepo
          Value: !Ref GitHubRepo
        - Key: ManagedBy
          Value: 'CloudFormation'

  # SSM Parameter to store the role ARN
  GitHubRoleArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: '/github-actions/troop202/role-arn'
      Type: String
      Value: !GetAtt GitHubActionsRole.Arn
      Description: 'ARN of the GitHub Actions IAM Role for Troop 202 website'
      Tags:
        Project: 'Troop202Website'
        ManagedBy: 'CloudFormation'

Outputs:
  GitHubActionsRoleArn:
    Description: 'ARN of the GitHub Actions IAM Role'
    Value: !GetAtt GitHubActionsRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-GitHubActionsRoleArn'
  
  GitHubActionsRoleName:
    Description: 'Name of the GitHub Actions IAM Role'
    Value: !Ref GitHubActionsRole
    Export:
      Name: !Sub '${AWS::StackName}-GitHubActionsRoleName'
  
  OIDCProviderArn:
    Description: 'ARN of the GitHub OIDC Identity Provider'
    Value: !Ref GitHubOIDCProvider
    Export:
      Name: !Sub '${AWS::StackName}-OIDCProviderArn'
  
  SetupInstructions:
    Description: 'Instructions for setting up GitHub repository secrets'
    Value: !Sub |
      Add the following secrets to your GitHub repository:
      
      AWS_ROLE_ARN=${GitHubActionsRole.Arn}
      HOSTED_ZONE_ID=<your-route53-hosted-zone-id>
      
      Repository: https://github.com/${GitHubOrg}/${GitHubRepo}/settings/secrets/actions