AWSTemplateFormatVersion: '2010-09-09'
Description: 'Basic monitoring for Troop 202 website - CloudWatch log groups only'

Parameters:
  Environment:
    Type: String
    Default: 'prod'
    AllowedValues: ['dev', 'staging', 'prod']
    Description: 'Environment name for resource naming'
  
  FoundationStackName:
    Type: String
    Default: 'troop202-foundation'
    Description: 'Name of the foundation stack to import resources from'

Resources:
  # CloudWatch Log Group for general monitoring
  WebsiteLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/cloudfront/${Environment}-troop202'
      RetentionInDays: 30
      KmsKeyId:
        Fn::ImportValue: !Sub '${FoundationStackName}-LogGroupKMSKeyArn'
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: 'CloudFormation'

  # CloudWatch Log Group for CloudFront access logs
  CloudFrontLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/cloudfront/access/${Environment}-troop202'
      RetentionInDays: 90
      KmsKeyId:
        Fn::ImportValue: !Sub '${FoundationStackName}-LogGroupKMSKeyArn'
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-troop202-cloudfront-logs'
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: 'CloudFormation'

Outputs:
  WebsiteLogGroup:
    Description: 'CloudWatch Log Group for general website monitoring'
    Value: !Ref WebsiteLogGroup
    Export:
      Name: !Sub '${AWS::StackName}-WebsiteLogGroup'
  
  CloudFrontLogGroup:
    Description: 'CloudWatch Log Group for CloudFront access logs'
    Value: !Ref CloudFrontLogGroup
    Export:
      Name: !Sub '${AWS::StackName}-CloudFrontLogGroup'