AWSTemplateFormatVersion: '2010-09-09'
Description: 'Shared KMS key for all Troop202 services - deploy once, use everywhere'

# NOTE: KMS keys are a massive pain in the ass in CloudFormation because:
# 1. They can't be easily updated or replaced due to dependencies
# 2. Tag changes require special permissions that are a nightmare to configure
# 3. Deletion has mandatory 7-day waiting periods that break dev workflows
# 4. Cross-stack references make them hard to clean up
# 
# Solution: One shared key for everything Troop202, stored in SSM for easy reference
# This key will be used by ALL Troop202 services (logs, S3, etc.)

Parameters:
  Environment:
    Type: String
    Default: 'prod'
    AllowedValues: ['dev', 'staging', 'prod']
    Description: 'Environment name'

Resources:
  # The one and only KMS key we'll ever need for Troop202
  # No tags because they're a pain to manage in CloudFormation
  # Simple policy that works for everything
  Troop202MasterKey:
    Type: AWS::KMS::Key
    Properties:
      Description: 'Troop202 master encryption key - used for all services (logs, S3, etc.)'
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
          - Sid: Allow CloudWatch Logs
            Effect: Allow
            Principal:
              Service: logs.amazonaws.com
            Action:
              - 'kms:Encrypt'
              - 'kms:Decrypt'
              - 'kms:ReEncrypt*'
              - 'kms:GenerateDataKey*'
              - 'kms:DescribeKey'
            Resource: '*'
          - Sid: Allow S3 Service
            Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action:
              - 'kms:Encrypt'
              - 'kms:Decrypt'
              - 'kms:ReEncrypt*'
              - 'kms:GenerateDataKey*'
              - 'kms:DescribeKey'
            Resource: '*'

  # Alias for the key
  Troop202MasterKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub 'alias/troop202-master-key'
      TargetKeyId: !Ref Troop202MasterKey

  # Store the key ARN in SSM so any stack can reference it
  # This is way better than cross-stack exports because it's more flexible
  KMSKeySSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: '/troop202/shared/kms-key-arn'
      Type: String
      Value: !GetAtt Troop202MasterKey.Arn
      Description: 'ARN of the shared Troop202 KMS key - use this in all stacks'

Outputs:
  KMSKeyArn:
    Description: 'ARN of the shared Troop202 KMS key'
    Value: !GetAtt Troop202MasterKey.Arn
    Export:
      Name: 'Troop202-Shared-KMS-Key-ARN'
  
  KMSKeyAlias:
    Description: 'Alias of the shared Troop202 KMS key'
    Value: !Ref Troop202MasterKeyAlias
  
  SSMParameterName:
    Description: 'SSM parameter containing the KMS key ARN'
    Value: !Ref KMSKeySSMParameter